import {
  BoldExtension,
  BulletListExtension,
  CodeBlockExtension,
  CodeExtension,
  HeadingExtension,
  ItalicExtension,
  ListItemExtension,
  OrderedListExtension,
  TaskListExtension,
  TaskListItemExtension,
  LinkExtension,
  MarkdownExtension,
  TableExtension,
  TableRowExtension,
  TableCellExtension,
  TableHeaderCellExtension,
  FontFamilyExtension,
  TextColorExtension,
  UnderlineExtension,
  TextHighlightExtension,
  TextCaseExtension,
  SupExtension,
  SubExtension,
  StrikeExtension,
  CalloutExtension,
  TextExtension,
  FontSizeExtension,
  ParagraphExtension,
  HistoryExtension,
  DocExtension,
  NodeFormattingExtension,
  BlockquoteExtension,
  HardBreakExtension,
} from "remirror/extensions";
import { CountExtension } from "@remirror/extension-count";

export const extensions = () => [
  new MarkdownExtension(),
  new LinkExtension({
    autoLink: true,
    openLinkOnClick: true,
  }),
  new ItalicExtension(),
  new CodeExtension(),
  new CodeBlockExtension(),
  new BoldExtension(),
  new SupExtension(),
  new SubExtension(),
  new StrikeExtension(),
  new HeadingExtension(),
  new TextCaseExtension(),
  new TextColorExtension(),
  new UnderlineExtension(),
  new TextHighlightExtension(),
  new CountExtension(),
  new TextExtension(),
  new FontSizeExtension(),
  new ParagraphExtension(),
  new HistoryExtension(),
  new DocExtension(),
  new NodeFormattingExtension(),
  new BlockquoteExtension(),
  new HardBreakExtension(),
  new CalloutExtension(),
  // List Extensions
  new BulletListExtension({
    enableSpine: true,
  }),
  new OrderedListExtension(),
  new ListItemExtension({
    enableCollapsible: true,
  }),
  new TaskListExtension(),
  new TaskListItemExtension(),

  // Table Extensions
  new TableExtension(),
  new TableRowExtension(),
  new TableCellExtension(),
  new TableHeaderCellExtension(),
  new FontFamilyExtension(),
];
